[loggers]
keys=root,api

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=detailFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_api]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=api
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=detailFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=detailFormatter
args=("api.log", "a")

[formatter_detailFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
